### ISSUE TITLE
Duplicate Key

### ISSUE THREAD

**Issue by smhmd** [optimizasean/TailwindAccessibilityConfig#1]
Key `'500'` is duplicated. I wouldn't know which one to take out.
https://github.com/optimizasean/TailwindAccessibilityConfig/blob/dabf18ed6a4911a8bdee860e727c7e0a21564900/tailwind.config.js#L88-L93

Also, this (`'500':`, as opposed to `500:`) is JSON syntax. The file could be formatted as a JavaScript object.

**Comment by dejangeci** [comment]
It looks like the duplicate key actually belongs to orange-warm-vivid according to
https://github.com/optimizasean/TailwindAccessibilityConfig/blob/master/tailwind.config.js.FANCY_NESTING_NOT_YET_SUPPORTED

```jsonc
'orange': {
  //
  '900': '#1b1614',
  'warm': {
    //
    '900': '#1c1615',
    'vivid': {
      //
      '500': '#d24302',
    },
  }
}
```

**Comment by optimizasean** [comment]
Yes that was a mistake, my bad.  I accidentally scrambled that one.  The syntax at the time (and as far as I know) is required to match that way so that the Tailwind generator utility can properly parse it, otherwise it cannot recognize it which is why it is JSON and not JavaScript object.
